services:
  - type: web
    name: flask-app
    env: docker
    plan: free
    region: oregon
    branch: main
    buildFilter:
      paths:
        - Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
